CREATE TABLE IF NOT EXISTS history_passwords (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_history_password_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);